# Stubs for quick_der.builder (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def build_asn1(context, recipe, bindata: Optional[Any] = ..., ofs: int = ..., outer_class: Optional[Any] = ...): ...
