# Stubs for quick_der.format (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def der_pack(value, hint: str = ..., der_packer: Optional[Any] = ..., cls: Optional[Any] = ...): ...
def der_format(value, hint: str = ...): ...
