# Stubs for quick_der.main (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from asn1ate.sema import *


def parse_opts(script_name, script_args): ...
def realise(incdirs, restargs): ...
def main(script_name, script_args): ...
