language: c
dist: trusty
sudo: false

addons:
  apt:
    packages:
      - cmake
      - python-dev


before_install:
  - sh ci/travis-continuous.sh

install:
  - make install

script:
  - make test

