language: c
dist: trusty
sudo: false

addons:
  apt:
    packages:
      - cmake
      - python-dev


before_install:
  - git describe
  - mkdir build
  - BUILDDIR=`pwd`/build SRCDIR=`pwd` sh ci/travis-continuous.sh

install:
  - ( cd build && make install )

script:
  - ( cd build && make test )

