
RFC4351 DEFINITIONS
IMPLICIT TAGS
EXTENSIBILITY IMPLIED ::=

        turnValue ::= SEQUENCE {
             mutual         BOOLEAN DEFAULT FALSE,
             identifier     LDAPString
        }

END
