PREFIX=/usr/local

all:

clean:

install:
	#
	# The hexio submodule did not arrive well in GIT
	#
	# If you need a good DER dumping utility, check it out yourself:
	# https://github.com/vanrein/hexio
	#
	@#NOTYET# install -m 0755 hexio/derdump.py "$(PREFIX)/bin/derdump"

uninstall:
	@#NOTYET# rm -f "$(PREFIX)/bin/derdump"

